[metadata]
addr = 0xbaa
size = 0x76
last_change = 2024-01-08T04:31:56.729686Z

[header]
last_change = 2024-01-08T04:31:56.729686Z
name = "write_into"
addr = 0xbaa
type = "void*"

[header.args.0]
offset = 0x0
name = "buf"
type = "void*"
size = 0x8

[header.args.1]
offset = 0x1
name = "arg2"
type = "int"
size = 0x4
